### PR TITLE
Fix Sound GQL query

### PR DESCRIPTION
**Pull request by puffo**

### CODE REVIEW

**Comment by musnit** [comment]
@puffo is this code still used?

**Comment by puffo** [comment]
The clean rebuild was failing to fetch metadata due to a  GQL validation error. Do you think we should do away with it entirely?

**Comment by musnit** [comment]
> The clean rebuild was failing to fetch metadata due to a GQL validation error. Do you think we should do away with it entirely?

was it from this function or somewhere else?

and yeah, potentially migrating to the multi-print that does no API query for the legacy sound.xyz tracks could be the best solution, though i haven't dug into it yet

**Comment by puffo** [comment]
Ok, this is not as much of a one liner as I'd hoped. Closing the PR for now and we'll tackle sound deprecations as a separate issue.

https://github.com/spinamp/spindexer/issues/118

**Pull request closed without merging**
